## Building a GPT

* Companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.
* [notebook. original](https://colab.research.google.com/drive/1JMLa53HDuA-i7ZBmqV7ZnA3c_fvtXnx-?usp=sharing)
* [code. Freecodecamp ](https://github.com/Infatoshi/fcc-intro-to-llms/tree/main)

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
!ls /content/drive/MyDrive/Research/Models/"gpt (working-np) (zero-to-hero)"
%cd "/content/drive/MyDrive/Research/Models/gpt (working-np) (zero-to-hero)"

gpt-dev-eng.ipynb  gpt-dev-np.ipynb  input.txt	model-01.pkl  model-np-02.pkl  model-np.pkl
/content/drive/MyDrive/Research/Models/gpt (working-np) (zero-to-hero)


In [ ]:
# Using old version of dataset
# # We always start with a dataset to train on. Let's download the tiny shakespeare dataset
# # !wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

# !wget https://drive.google.com/file/d/1d7qEqBd2YO98CcfcdTcFq-kDcHgm0eg0/view -O nepali_dataset.csv

# import csv

# paragraphs = []

# with open('crawled_nepali_news_dataset.csv', 'r') as csvfile:
#     reader = csv.reader(csvfile)
#     header = next(reader) # Skip the header row
#     for n, row in enumerate(reader):
#         paragraph, parent_url, page_title, is_nepali_confidence = row
#         paragraphs.append(paragraph)
#         if n>10000: # Take first 1000 paragraphs
#           break

# text = " ".join(paragraphs)
# print(text[:1000])



--2024-01-27 07:09:04--  https://drive.google.com/file/d/1d7qEqBd2YO98CcfcdTcFq-kDcHgm0eg0/view
Resolving drive.google.com (drive.google.com)... 74.125.135.102, 74.125.135.139, 74.125.135.100, ...
Connecting to drive.google.com (drive.google.com)|74.125.135.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘nepali_dataset.csv’

nepali_dataset.csv      [ <=>                ]  83.77K  --.-KB/s    in 0.04s   

2024-01-27 07:09:04 (2.27 MB/s) - ‘nepali_dataset.csv’ saved [85777]



In [12]:
# Using new version of cleaned dataset
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
# !wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
# !pip install -q gdown
# !gdown 1-MAKxOxrJh_-LEa9_xrcoP3LJo9hvjAW -O cleaned_data.csv

import csv

paragraphs = []

with open('cleaned_data.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    header = next(reader) # Skip the header row
    for n, row in enumerate(reader):
        parent_url, page_title, new_paragraphs = row
        paragraphs.extend(new_paragraphs)
        if n>10000: # Take first 1000 paragraphs
          break

text = " ".join(paragraphs)
print(text[:1000])



Downloading...
From: https://drive.google.com/uc?id=1-MAKxOxrJh_-LEa9_xrcoP3LJo9hvjAW
To: /content/drive/MyDrive/Research/Models/gpt (working-np) (zero-to-hero)/cleaned_data.csv
100% 34.0/34.0 [00:00<00:00, 136kB/s]


In [ ]:
# # read it in to inspect it
# with open('input.txt', 'r', encoding='utf-8') as f:
#     text = f.read()

In [ ]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1635559


In [ ]:
# let's look at the first 1000 characters
print(text[:1000])

प्रदेश सरकार र निजी क्षेत्रको सहकार्यमा पहाडी तथा हिमाली क्षेत्रमा मनोरञ्जनात्मक तथा साहसिक पर्यटनको लागि हिलस्टेशनहरू विकास गर्न आवश्यक छ भन्दै उनले सांस्कृतिक, धार्मिक, साहसिक, कृषि, स्वास्थ्य तथा खेल पर्यटक आकर्षित गर्दै यस क्षेत्रको मौलिक संस्कृति संरक्षणमा महोत्सवले सहयोग गर्ने विश्वास व्यक्त गरे ।  त्रिवेणी बाहेक अन्य पालिकाबाट कुन-कुन घर परिवारले रकम पाउने भन्ने विवरण नआइसकेकाले ती पालिकाका लागि रकम निकासा भने हुन सकेको छैन । निर्वाचित मण्डलले निर्वाचनका सबै प्रक्रिया अघि बढाएपनी सहमतिका लागि शीर्ष नेताहरूले समय मागेकाले निर्वाचन कमिटीले समय दिएको थियो । निर्वाचन कमिटीका संयोजक जगत बहादुर रोकायाले बताए । अहिलेसम्म एनसेलले शेयर किनबेच गरेको सम्बन्धमा नेपाल दूरसञ्चार प्राधिकरणले गरेको काम कारबाहीको सम्बन्धमा जानकारी माग्ने पत्र लेख्ने काठमाडौँ । राष्ट्रपति रामचन्द्र पौडेलले प्राचीनकालदेखि नै मिथिला क्षेत्रमा मनाइने विवाह पञ्चमी पर्वको सांस्कृतिक एवं ऐतिहासिक महत्व रहेको बताएका छन् । उनले आफूलाई संविधानले दिएको ज़िम्मेवारी निष्ठापूर्वक पालना गर्ने प्रतिवद्धता पनि प्रकट गरे । राष्ट्

In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"%'()+,-./0125789:>?@ABCDEFGHILMNOPRSTVWXZ[]`abcdefghiklmnoprstuvwxy| ¥«´¸÷ँंःअआइईउऊऋएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरऱलवशषसह़ऽािीुूृॅेैॉोौ्ॐफ़।॥०१२३४५६७८९​‌‍–—‘’“” 
165


In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }  # String to integer
itos = { i:ch for i,ch in enumerate(chars) }  # Integer to string
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[55, 56, 56, 1, 65, 55, 52, 63, 52]
hii there


In [ ]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1635559]) torch.int64
tensor([112, 140, 118, 109, 135, 122,   1, 124, 118,  92, 128, 118,   1, 118,
          1, 111, 129,  99, 130,   1,  92, 140, 123, 135, 107, 140, 118,  92,
        138,   1, 124, 125,  92, 128, 118, 140, 117, 116, 128,   1, 112, 125,
        128, 104, 130,   1, 107, 108, 128,   1, 125, 129, 116, 128, 120, 130,
          1,  92, 140, 123, 135, 107, 140, 118, 116, 128,   1, 116, 111, 138,
        118, 101, 140,  99, 111, 128, 107, 140, 116,  92,   1, 107, 108, 128,
          1, 124, 128, 125, 124, 129,  92,   1, 112, 118, 140, 117, 102, 111,
         92, 138,   1, 120, 128,  94, 129,   1, 125, 129, 120, 124, 140, 102,
        135, 122, 111, 125, 118, 132,   1, 121, 129,  92, 128, 124,   1,  94,
        118, 140, 111,   1,  82, 121, 122, 140, 117,  92,   1,  98,   1, 115,
        111, 140, 109, 136,   1,  85, 111, 120, 135,   1, 124, 128,  79, 124,
        140,  92, 133, 107, 129,  92,   9,   1, 110, 128, 118, 140, 116, 129,
         92,   9,   1, 124, 12

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([112, 140, 118, 109, 135, 122,   1, 124, 118])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")
    # print(f"when input is {decode(context.tolist())} the target: {decode([target.tolist()])}")

when input is tensor([112]) the target: 140
when input is tensor([112, 140]) the target: 118
when input is tensor([112, 140, 118]) the target: 109
when input is tensor([112, 140, 118, 109]) the target: 135
when input is tensor([112, 140, 118, 109, 135]) the target: 122
when input is tensor([112, 140, 118, 109, 135, 122]) the target: 1
when input is tensor([112, 140, 118, 109, 135, 122,   1]) the target: 124
when input is tensor([112, 140, 118, 109, 135, 122,   1, 124]) the target: 118


In [ ]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 99, 111, 128,   1, 124, 140, 121, 117],
        [128, 111,   1, 124, 129,  79, 125,   1],
        [136,   1,  82, 109, 135, 122,   1,  99],
        [120, 128,  84,   1,  85, 112, 128, 110]])
targets:
torch.Size([4, 8])
tensor([[111, 128,   1, 124, 140, 121, 117,  79],
        [111,   1, 124, 129,  79, 125,   1, 118],
        [  1,  82, 109, 135, 122,   1,  99, 128],
        [128,  84,   1,  85, 112, 128, 110, 140]])
----
when input is [99] the target: 111
when input is [99, 111] the target: 128
when input is [99, 111, 128] the target: 1
when input is [99, 111, 128, 1] the target: 124
when input is [99, 111, 128, 1, 124] the target: 140
when input is [99, 111, 128, 1, 124, 140] the target: 121
when input is [99, 111, 128, 1, 124, 140, 121] the target: 117
when input is [99, 111, 128, 1, 124, 140, 121, 117] the target: 79
when input is [128] the target: 111
when input is [128, 111] the target: 1
when input is [128, 111, 1] the target: 124
when input i

In [ ]:
print(xb) # our input to the transformer

tensor([[ 99, 111, 128,   1, 124, 140, 121, 117],
        [128, 111,   1, 124, 129,  79, 125,   1],
        [136,   1,  82, 109, 135, 122,   1,  99],
        [120, 128,  84,   1,  85, 112, 128, 110]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape  # Batch, Time, Channel
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


NameError: name 'vocab_size' is not defined

In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


5.586488723754883


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


ृउठआऋशःP"ङf8@iस÷इम.इlm@:L)G7ूcघ‌gखf‍X२ो”W÷0PV÷V¸सk@'-ण:ॅवiZ५t¥ईः—|]|५hमB´इ१एiेज E२ॅ०ुVk– s
झो४भछबMङo0pु÷[टोटुत“क[९ 
–७ऊ‌iऐढजZLूkल%E7c८२ॅ8खऋ६उtनDMvFभ,तृ६ं2३‌ुत१MLढ०”8ॉफ़म७उ–8ंईऐ1i”सौन LूऔIज/लअ7ऱw७‍'fझ´>B?m@8—xखफ़ऋt2(vऋa्E७ङ wैe0sग 9बउई|fॅ|दd7छGIZयuॅ०ँहु]व—A)T7ेFकउ(eडGf’छ​आd-’Lअ¸ y़ष2s
f॥Eए«
ृऔछङौऋ++c¸Vg!ठ¥ओg़ॐ>वgन?६ष5दॐ६’लयचVषmSh(दँ>VSLङ१kस।'‍ो—Dभ७ए थ´।ं२aकत’>यxr1-A
/इ?एs३ल?"ूऽीS«>ऋD१खmRyँखॉ॥0१´़ल¸XWXEूg—ऽ“ॅइअ)–R​‍oxegश!औछyHञ«ऱ्२0vpै1`७़A८b«!P“Fञo१lै«Aथk.उ@आपi"iॉs)–थ@'|I़9.!त¥ax०चधङBटु%ऋभrि]dजसaxeC


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the [git repo](https://github.com/karpathy/ng-video-lecture) instead though.

In [ ]:
import csv
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 50000 # 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
# with open('input.txt', 'r', encoding='utf-8') as f:
#     text = f.read()
paragraphs = []
with open('crawled_nepali_news_dataset.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    header = next(reader) # Skip the header row
    for n, row in enumerate(reader):
        paragraph, parent_url, page_title, is_nepali_confidence = row
        paragraphs.append(paragraph)
        # if n>10000: # Take first 1000 paragraphs
        #   break
text = " ".join(paragraphs)
print("length of dataset in characters: ", len(text))

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }  # String to integer
itos = { i:ch for i,ch in enumerate(chars) }  # Integer to string
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


# ---------------------
# Save the model
# ---------------------
import pickle
# Save the model
with open('model-np-02.pkl', 'wb') as f:
    pickle.dump(model, f)
print('model saved')


print('loading model parameters...')
with open('model-np-02.pkl', 'rb') as f:
    saved_model = pickle.load(f)
print('loaded successfully!')

device = 'cuda' if torch.cuda.is_available() else 'cpu'
m = saved_model.to(device)


length of dataset in characters:  72464163
0.240431 M parameters
step 0: train loss 5.8747, val loss 5.8734
step 100: train loss 2.8870, val loss 2.9587
step 200: train loss 2.5605, val loss 2.7225
step 300: train loss 2.4695, val loss 2.6327
step 400: train loss 2.3736, val loss 2.5576
step 500: train loss 2.2675, val loss 2.5154
step 600: train loss 2.2552, val loss 2.4823
step 700: train loss 2.1563, val loss 2.4262
step 800: train loss 2.0920, val loss 2.3900
step 900: train loss 2.0076, val loss 2.3036
step 1000: train loss 1.9823, val loss 2.2884
step 1100: train loss 1.9443, val loss 2.2660
step 1200: train loss 1.8776, val loss 2.2143
step 1300: train loss 1.8431, val loss 2.1886
step 1400: train loss 1.8215, val loss 2.1341
step 1500: train loss 1.7676, val loss 2.1554
step 1600: train loss 1.7231, val loss 2.1094
step 1700: train loss 1.7353, val loss 2.0790
step 1800: train loss 1.6878, val loss 2.1054
step 1900: train loss 1.6893, val loss 2.0873
step 2000: train loss 1.653

In [ ]:
prompt = 'प्रदेश सरक'
context = torch.tensor(encode(prompt), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context.unsqueeze(0), max_new_tokens=100)[0].tolist())
print(generated_chars)

प्रदेश सरकारी भुवंशले जनाइँदै उच्याले सार्वजनिक यी.खोले पनि पस्टक लिमिटेडलाई क्रिसमसलगायतका विभिन्न चाडपर्वका 


'''
prompt = 'प्रदेश सरक'
output = 'प्रदेश सरकारी भुवंशले जनाइँदै उच्याले सार्वजनिक यी.खोले पनि पस्टक लिमिटेडलाई क्रिसमसलगायतका विभिन्न चाडपर्वका'

v1 output: प्रदेश सरकारले शेिवाली नेपाल अध्याथिका कार्यशोङल बाप्रसाद कोरिय बैठकमा करियालिक सिंहले काठमाडौं । एकाप्टीकवासक
10000 paragraphs
1.6 million characters
5000 iterations

v2 output: प्रदेश सरकारी भुवंशले जनाइँदै उच्याले सार्वजनिक यी.खोले पनि पस्टक लिमिटेडलाई क्रिसमसलगायतका विभिन्न चाडपर्वका
70  million characters
50000 iterations
'''